export const colleges = [
    {
        rank: 20,
        colleges: [
            "Indian Institute of Technology Madras",
            "Indian Institute of Technology Delhi",
            "Indian Institute of Technology Bombay",
            "Indian Institute of Technology Kanpur",
            "Indian Institute of Technology Kharagpur",
            "Indian Institute of Technology Roorkee",
            "Indian Institute of Technology Guwahati",
            "Indian Institute of Technology Hyderabad",
            "National Institute of Technology Tiruchirappalli",
            "Indian Institute of Technology Indore",
            "Indian Institute of Technology (BHU) Varanasi",
            "Indian Institute of Technology (Indian School of Mines)",
            "National Institute of Technology Karnataka",
            "Anna University",
            "Vellore Institute of Technology",
            "National Institute of Technology Rourkela",
            "Jadavpur University",
            "Institute of Chemical Technology",
            "National Institute of Technology Warangal",
            "Amrita School of Engineering",
            "Indian Institute of Engineering Science and Technology",
            "Indian Institute of Technology Bhubaneswar",
            "National Institute of Technology Calicut",
            "Indian Institute of Technology Gandhinagar"
        ],
        location: [
            "Chennai",
            "New Delhi",
            "Mumbai",
            "Kanpur",
            "Kharagpur",
            "Roorkee",
            "Guwahati",
            "Hyderabad",
            "Tiruchirappalli",
            "Indore",
            "Varanasi",
            "Dhanbad",
            "Surathkal",
            "Chennai",
            "Vellore",
            "Rourkela",
            "Kolkata",
            "Mumbai",
            "Warangal",
            "Amritapuri",
            "Shibpur",
            "Bhubaneswar",
            "Kozhikode",
            "Gandhinagar",
        ]
    },
    {
        rank: 500,
        colleges: [
            "Indian Institute of Technology Ropar",
            "Indian Institute of Technology Patna",
            "Visvesvaraya National Institute of Technology",
            "Jamia Millia Islamia",
            "Thapar Institute of Engineering & Technology",
            "Birla Institute of Technology & Science",
            "Indian Institute of Technology Mandi",
            "Amity University Noida",
            "Indian Institute of Space Science and Technology",
            "Siksha `O` Anusandhan",
            "Malaviya National Institute of Technology",
            "Delhi Technological University",
            "Shanmugha Arts Science Technology & Research Academy",
            "Birla Institute of Technology",
            "Aligarh Muslim University",
            "National Institute of Technology Kurukshetra",
            "S. R. M. Institute of Science and Technology",
            "Kalinga Institute of Industrial Technology",
            "International Institute of Information Technology Hyderabad",
            "Sri Sivasubramaniya Nadar College of Engineering",
            "Manipal Institute of Technology",
            "National Institute of Technology Silchar",
            "National Institute of Technology Durgapur"
        ],
        location: [
            "Ropar",
            "Patna",
            "Nagpur",
            "New Delhi",
            "Patiala",
            "Pilani",
            "Mandi",
            "Gautam Budh Nagar",
            "Thiruvananthapuram",
            "Bhubaneswar",
            "Jaipur",
            "New Delhi",
            "Thanjavur",
            "Ranchi",
            "Aligarh",
            "Kurukshetra",
            "Chennai",
            "Bhubaneswar",
            "Hyderabad",
            "Kancheepuram",
            "Manipal",
            "Silchar",
            "Durgapur"
        ]
    },
    {
        rank: 2000,
        colleges: [
            "Motilal Nehru National Institute of Technology",
            "College of Engineering Pune",
            "Sathyabama Institute of Science and Technology",
            "Dr. B. R. Ambedkar National Institute of Technology",
            "Indian Institute of Technology Jodhpur",
            "Sardar Vallabhbhai National Institute of Technology",
            "Visvesvaraya Technological University",
            "Indraprastha Institute of Information Technology Delhi",
            "Jawaharlal Nehru Technological University",
            "Koneru Lakshmaiah Education Foundation University",
            "M. S. Ramaiah Institute of Technology",
            "Kalasalingam Academy of Research and Higher Education",
            "National Institute of Technology Meghalaya",
            "International Institute of Information Technology Bangalore",
            "Defence Institute of Advanced Technology",
            "Thiagarajar College of Engineering",
            "Maulana Azad National Institute of Technology",
            "Indian Institute of Information Technology Guwahati",
        ],
        location: [
            "Allahabad",
            "Pune",
            "Chennai",
            "Jalandhar",
            "Jodhpur",
            "Surat",
            "Belgaum",
            "New Delhi",
            "Hyderabad",
            "Vaddeswaram",
            "Bengaluru",
            "Srivilliputtur",
            "Shillong",
            "Bengaluru",
            "Pune",
            "Madurai",
            "Bhopal",
            "Guwahati",
        ]
    },
    {
        rank: 4000,
        colleges: [
            "National Institute of Technology Raipur",
            "Punjab Engineering College (Deemed To Be University)",
            "College of Engineering(A)",
            "R. V. College of Engineering",
            "Veermata Jijabai Technological Institute",
            "Panjab University",
            "B.M.S. College of Engineering",
            "Indian Institute of Food Processing Technology (IIFPT)",
            "National Institute of Technology Agartala",
            "Netaji Subhas University of Technology (NSUT)",
            "National Institute of Technology Goa",
            "Shri Mata Vaishno Devi University",
            "National Institute of Technology Jamshedpur",
            "Karunya Institute of Technology and Sciences",
            "Indian Institute of Information Technology Design & Manufacturing Jabalpur",
            "Kumaraguru College of Technology",
            "Sri Krishna College of Engineering and Technology",
            "Chandigarh University",
            "College of Engineering Trivandrum",
        ],
        location: [
            "Raipur",
            "Chandigarh",
            "Visakhapatnam",
            "Bengaluru",
            "Mumbai",
            "Chandigarh",
            "Bengaluru",
            "Thanjavur",
            "Agratala",
            "South West",
            "Ponda",
            "Katra",
            "Jamshedpur",
            "Coimbatore",
            "Jabalpur",
            "Coimbatore",
            "Coimbatore",
            "Mohali",
            "Thiruvananthapuram",
        ]
    },
    {
        rank: 15700,
        colleges: [
            "Guru Gobind Singh Indraprastha University",
            "Lovely Professional University",
            "University College of Engineering",
            "Graphic Era University",
            "Coimbatore Institute of Technology",
            "Siddaganga Institute of Technology",
            "National Institute of Technology Patna",
            "C.V. Raman Global University",
            "PES University",
            "Vel Tech Rangarajan Dr. Sagunthala R & D Institute of Science and Technology",
            "Jaypee Institute of Information Technology",
            "University College of Engineering",
            "National Institute of Technology Hamirpur",
            "Bharati Vidyapeeth Deemed University College of Engineering",
            "Atal Bihari Vajpayee Indian Institute of Information Technology and Management",
        ],
        location: [
            "New Delhi",
            "Phagwara",
            "Hyderabad",
            "Dehradun",
            "Coimbatore",
            "Tumkur",
            "Patna",
            "Bhubaneswar",
            "Bengaluru",
            "Chennai",
            "Noida",
            "Kakinada",
            "Hamirpur",
            "Pune",
            "Gwalior",
        ]
    }
]